import Image from "next/image";
import { authOptions } from "@/app/api/auth/[...nextauth]/route";
import { getServerSession } from "next-auth";
import { Inter } from "next/font/google";
import "../globals.css";
import AppSidebar from "@/components/layout/AppSidebar";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default async function AppLayout({ children }) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen">
          <div className="flex w-48 flex-col bg-white p-4 shadow">
            <Image
              src={session?.user?.image}
              alt={"avataar"}
              width={80}
              height={60}
              className="mx-auto my-8 rounded-full"
            />
            <AppSidebar />
          </div>
          <div className="flex-1 bg-gray-100 p-5">{children}</div>
        </main>
      </body>
    </html>
  );
}
